/*
 * Tablor ui_chain.js — the module-owned editor (the 9W9 treatment).
 *
 *   - Jog wheel: previous / next page (16 pages).
 *   - Shift + jog: jump to the next SECTION (Osc, Filter, Env, LFO, Mod,
 *     Global, User) — skipping the section's extra pages.
 *   - Knobs 1-8: edit the visible page's 8 slots. Wavetable slots STEP
 *     THROUGH THE FILES directly (list served by the DSP as wt_files);
 *     no browser needed — turn encoder 1, hear the next table.
 *   - USER page: hold Shift and turn a knob to assign ANY parameter to
 *     that slot (cycles the full parameter list); release Shift to play.
 *     Assignments persist in user_map.json next to the module.
 *   - Back: exits to the chain editor (never consumed).
 *
 * Pads are untouched — they pass to Move as always. Focus-gated: this UI
 * only reacts while its own slot is the one focused in the chain UI.
 *
 * Page data is generated by tools/gen_params.py into ui_pages.json —
 * the same single source as chain_params and movy_config.
 *
 * Dial drawing after 9W9 (GPL-3.0), itself in the style of Movy (MIT).
 */

(function () {
    "use strict";

    var MODULE_DIR = "/data/UserData/schwung/modules/sound_generators/tablor";

    var PAGES = [];        /* from ui_pages.json */
    var SECTIONS = [];     /* [{name, firstPage}] */
    var ALLPARAMS = [];    /* flat slot list for USER assignment */

    var mySlot = -1;
    var pageIdx = 0;
    var vals = {};         /* key -> value (number for int/enum, string for file) */
    var dirty = true;
    var lastTouched = -1;
    var lastHeader = "";   /* right-aligned header text (value readout) */
    var wtFiles = null;    /* cached wt_files list */
    var wtFilesAge = 0;
    var userMap = [null, null, null, null, null, null, null, null];
    var assignFlash = 0;

    function has(fn) { return typeof globalThis[fn] === "function"; }
    function uiSlot() { return has("shadow_get_ui_slot") ? shadow_get_ui_slot() : 0; }
    function isFocused() { return mySlot >= 0 && uiSlot() === mySlot; }
    function relDelta(v) { return v < 64 ? v : v - 128; }

    function baseName(path) {
        if (!path) return "Init";
        var i = path.lastIndexOf("/");
        var n = i >= 0 ? path.substring(i + 1) : path;
        var d = n.lastIndexOf(".");
        return d > 0 ? n.substring(0, d) : n;
    }

    /* ---------------- data ---------------- */

    function loadPages() {
        var txt = has("host_read_file")
            ? host_read_file(MODULE_DIR + "/ui_pages.json") : null;
        if (!txt) return false;
        var data;
        try { data = JSON.parse(txt); } catch (e) { return false; }
        PAGES = data.pages || [];

        SECTIONS = [];
        ALLPARAMS = [];
        var lastSec = null;
        for (var i = 0; i < PAGES.length; i++) {
            if (PAGES[i].sec !== lastSec) {
                SECTIONS.push({ name: PAGES[i].sec, firstPage: i });
                lastSec = PAGES[i].sec;
            }
            var slots = PAGES[i].slots || [];
            for (var s = 0; s < slots.length; s++)
                if (slots[s]) ALLPARAMS.push(slots[s]);
        }
        /* USER page is ours, appended after the generated ones */
        PAGES.push({ name: "USER", sec: "User", slots: userSlots() });
        SECTIONS.push({ name: "User", firstPage: PAGES.length - 1 });
        return true;
    }

    function userSlots() {
        var out = [];
        for (var i = 0; i < 8; i++) {
            var key = userMap[i];
            var slot = null;
            if (key)
                for (var j = 0; j < ALLPARAMS.length; j++)
                    if (ALLPARAMS[j].k === key) { slot = ALLPARAMS[j]; break; }
            out.push(slot);
        }
        return out;
    }

    function loadUserMap() {
        var txt = has("host_read_file")
            ? host_read_file(MODULE_DIR + "/user_map.json") : null;
        if (!txt) return;
        try {
            var m = JSON.parse(txt);
            if (m && m.length === 8) userMap = m;
        } catch (e) {}
    }

    function saveUserMap() {
        if (has("host_write_file"))
            host_write_file(MODULE_DIR + "/user_map.json", JSON.stringify(userMap));
    }

    function readParam(slot) {
        if (!has("shadow_get_param")) return slot.t === "file" ? "" : 0;
        var raw = shadow_get_param(uiSlot(), "synth:" + slot.k);
        if (raw === null || raw === undefined) raw = "";
        if (slot.t === "file") return String(raw);
        if (slot.t === "enum") {
            var opts = slot.options || [];
            for (var i = 0; i < opts.length; i++)
                if (opts[i] === raw) return i;
            var n = parseInt(raw, 10);
            return isNaN(n) ? 0 : n;
        }
        var v = parseFloat(raw);
        return isNaN(v) ? 0 : Math.round(v);
    }

    function loadPage() {
        var slots = PAGES[pageIdx].slots;
        for (var i = 0; i < slots.length; i++)
            if (slots[i]) vals[slots[i].k] = readParam(slots[i]);
        dirty = true;
    }

    function getWtFiles() {
        var now = Date.now();
        if (wtFiles && now - wtFilesAge < 4000) return wtFiles;
        var raw = has("shadow_get_param")
            ? shadow_get_param(uiSlot(), "synth:wt_files") : "";
        wtFiles = [];
        if (raw) {
            var parts = String(raw).split("\n");
            for (var i = 0; i < parts.length; i++)
                if (parts[i]) wtFiles.push(parts[i]);
        }
        wtFilesAge = now;
        return wtFiles;
    }

    /* ---------------- edits ---------------- */

    function setParam(key, val) {
        if (has("shadow_set_param"))
            shadow_set_param(uiSlot(), "synth:" + key, String(val));
    }

    function stepFile(slot, delta) {
        var files = getWtFiles();
        var cur = vals[slot.k] || "";
        var idx = -1;
        for (var i = 0; i < files.length; i++)
            if (files[i] === cur) { idx = i; break; }
        /* position -1 = built-in Init; stepping down from Init wraps to end */
        idx += delta > 0 ? 1 : -1;
        var next;
        if (idx < -1) { next = files.length ? files[files.length - 1] : ""; }
        else if (idx < 0 || idx >= files.length) { next = ""; }   /* Init */
        else next = files[idx];
        vals[slot.k] = next;
        setParam(slot.k, next);
        lastHeader = baseName(next);
        dirty = true;
    }

    function adjustKnob(ki, delta) {
        var page = PAGES[pageIdx];
        var slot = page.slots[ki];
        lastTouched = ki;
        if (!slot) { dirty = true; return; }

        if (slot.t === "file") { stepFile(slot, delta); return; }

        var max = slot.t === "enum" ? (slot.options.length - 1) : (slot.max | 0);
        var min = slot.t === "enum" ? 0 : (slot.min | 0);
        var step = slot.t === "enum" ? (delta > 0 ? 1 : -1) : delta;
        var v = (vals[slot.k] | 0) + step;
        if (v < min) v = min;
        if (v > max) v = max;
        if (v !== vals[slot.k]) {
            vals[slot.k] = v;
            setParam(slot.k, v);
        }
        lastHeader = slot.t === "enum" ? (slot.options[v] || "?") : String(v);
        dirty = true;
    }

    /* USER page: Shift+turn cycles the assignment through every parameter. */
    function assignUserSlot(ki, delta) {
        var cur = userMap[ki];
        var idx = -1;
        for (var i = 0; i < ALLPARAMS.length; i++)
            if (ALLPARAMS[i].k === cur) { idx = i; break; }
        idx += delta > 0 ? 1 : -1;
        if (idx < -1) idx = ALLPARAMS.length - 1;
        if (idx >= ALLPARAMS.length) idx = -1;      /* -1 = unassigned */
        userMap[ki] = idx < 0 ? null : ALLPARAMS[idx].k;
        PAGES[PAGES.length - 1].slots = userSlots();
        saveUserMap();
        loadPage();
        lastTouched = ki;
        lastHeader = idx < 0 ? "--" : ALLPARAMS[idx].full;
        assignFlash = Date.now();
        dirty = true;
    }

    function selectPage(idx, announce) {
        var n = PAGES.length;
        pageIdx = ((idx % n) + n) % n;
        loadPage();
        lastTouched = -1;
        lastHeader = "";
        if (announce && has("host_announce_screenreader"))
            host_announce_screenreader("Tablor " + PAGES[pageIdx].name);
        dirty = true;
    }

    function jumpSection(dir) {
        var cur = 0;
        for (var i = 0; i < SECTIONS.length; i++)
            if (SECTIONS[i].firstPage <= pageIdx) cur = i;
        var n = SECTIONS.length;
        var next = ((cur + (dir > 0 ? 1 : n - 1)) % n);
        selectPage(SECTIONS[next].firstPage, true);
    }

    /* ---------------- drawing (128x64, 1-bit) ---------------- */

    var DIAL_R = 6;
    var CIRC = [];
    (function () {
        for (var a = 0; a < 32; a++) {
            var t = (a / 32) * 6.28318;
            CIRC.push([Math.round(Math.cos(t) * DIAL_R),
                       Math.round(Math.sin(t) * DIAL_R)]);
        }
    })();

    function drawDial(cx, cy, v01) {
        var i;
        for (i = 0; i < CIRC.length; i++)
            set_pixel(cx + CIRC[i][0], cy + CIRC[i][1], 1);
        var ang = (225 - v01 * 270) * 0.0174533;
        var dx = Math.cos(ang), dy = -Math.sin(ang);
        for (i = 1; i <= DIAL_R - 1; i++)
            set_pixel(Math.round(cx + dx * i), Math.round(cy + dy * i), 1);
        set_pixel(cx, cy, 1);
    }

    function drawPageBar() {
        /* one tick per page along the bottom; gaps between sections;
         * current page is a taller tick — Movy's bankbar idea. */
        var n = PAGES.length;
        var secOf = [];
        for (var i = 0; i < n; i++) {
            var s = 0;
            for (var j = 0; j < SECTIONS.length; j++)
                if (SECTIONS[j].firstPage <= i) s = j;
            secOf.push(s);
        }
        var w = Math.max(3, Math.floor((128 - SECTIONS.length * 2) / n));
        var x = 1;
        for (i = 0; i < n; i++) {
            if (i > 0 && secOf[i] !== secOf[i - 1]) x += 2;
            var h = i === pageIdx ? 3 : 1;
            fill_rect(x, 63 - h, w - 1, h, 1);
            x += w;
        }
    }

    function draw() {
        clear_screen();
        var page = PAGES[pageIdx];

        fill_rect(0, 0, 128, 9, 1);
        print(2, 1, "TBL " + page.name, 0);
        if (lastHeader) {
            var t = lastHeader;
            while (text_width(t) > 66 && t.length > 1)
                t = t.substring(0, t.length - 1);
            print(126 - text_width(t), 1, t, 0);
        }

        var isUser = pageIdx === PAGES.length - 1;
        for (var i = 0; i < 8; i++) {
            var slot = page.slots[i];
            var x = (i % 4) * 32;
            var y = i < 4 ? 12 : 37;
            if (!slot) {
                if (isUser) print(x + 13, y + 6, "--", 1);
                continue;
            }
            var v = vals[slot.k];
            if (slot.t === "file") {
                draw_rect(x + 1, y + 1, 30, 12, 1);
                var name = baseName(v);
                while (text_width(name) > 26 && name.length > 1)
                    name = name.substring(0, name.length - 1);
                print(x + 3, y + 3, name, 1);
            } else if (slot.t === "enum") {
                var txt = (slot.options[v] || "?").substring(0, 5);
                draw_rect(x + 2, y + 1, 28, 12, 1);
                print(x + 4 + ((24 - text_width(txt)) >> 1), y + 3, txt, 1);
            } else {
                var range = (slot.max | 0) - (slot.min | 0);
                var v01 = range > 0 ? ((v - (slot.min | 0)) / range) : 0;
                drawDial(x + 15, y + 6, v01);
            }
            var lbl = slot.n.substring(0, 5);
            print(x + ((32 - text_width(lbl)) >> 1), y + 14, lbl, 1);
        }

        drawPageBar();
        dirty = false;
    }

    /* ---------------- chain_ui hooks ---------------- */

    function init() {
        mySlot = uiSlot();
        loadUserMap();
        if (!loadPages()) {
            PAGES = [{ name: "NO DATA", sec: "?", slots: [] }];
            SECTIONS = [{ name: "?", firstPage: 0 }];
        }
        selectPage(0, false);
        if (has("host_announce_screenreader"))
            host_announce_screenreader("Tablor");
    }

    function tick() {
        var shown = !has("shadow_get_display_mode") || shadow_get_display_mode() === 1;
        if (!shown || !isFocused()) return;
        if (assignFlash && Date.now() - assignFlash > 1200) {
            assignFlash = 0;
            dirty = true;
        }
        if (dirty) draw();
    }

    function onMidiMessageInternal(data) {
        if (!isFocused()) return;

        var status = data[0] & 0xF0;
        var d1 = data[1];
        var d2 = data[2];

        if (status !== 0xB0) return;

        var shiftHeld = has("shadow_get_shift_held") && shadow_get_shift_held();

        /* knobs 1-8 */
        if (d1 >= 71 && d1 <= 78 && d2 > 0) {
            var ki = d1 - 71;
            if (shiftHeld && pageIdx === PAGES.length - 1)
                assignUserSlot(ki, relDelta(d2));
            else
                adjustKnob(ki, relDelta(d2));
            return;
        }

        /* jog wheel */
        if (d1 === 14 && d2 > 0) {
            var d = relDelta(d2);
            if (shiftHeld) jumpSection(d);
            else selectPage(pageIdx + (d > 0 ? 1 : -1), true);
            return;
        }
    }

    function onMidiMessageExternal(data) {}

    function handleBack() { return false; }

    globalThis.chain_ui = {
        init: init,
        tick: tick,
        onMidiMessageInternal: onMidiMessageInternal,
        onMidiMessageExternal: onMidiMessageExternal,
        handleBack: handleBack
    };
})();
